### ISSUE TITLE
使用MultiTypeView 在滑到第11个itme后报强转类型报错

### ISSUE THREAD

**Issue by xianningqis** [LuckyJayce/MultiTypeView#7]

**Comment by xianningqis** [comment]
java.lang.ClassCastException: android.widget.ImageView cannot be cast to android.view.ViewGroup
        at android.support.v4.app.FragmentTransition.configureTransitionsOrdered(FragmentTransition.java:310)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:134)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at com.dounion.dosmart.mylibrary.provider.FragmentDataProvider.onViewAttachedToWindow(FragmentDataProvider.java:74)
        at com.dounion.dosmart.mylibrary.MultiTypeAdapter.onViewAttachedToWindow(MultiTypeAdapter.java:196)
        at android.support.v7.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7161)
        at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:782)
        at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
        at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8222)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8180)
        at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8168)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1573)
